fragment ProductsParts on Products {
  __typename
  title
  image
  length
  material
  maxLoad
  seo {
    __typename
    metaTitle
    metaDescription
  }
}

fragment PostParts on Post {
  __typename
  title
  publishDate
  image
  excerpt
  body
  seo {
    __typename
    metaTitle
    metaDescription
  }
}
